### ISSUE TITLE
Issue with SumOfLine function in Day1-part1

### ISSUE THREAD

**Issue by Mr-Unforgettable** [Aadv1k/AdventOfGo2023#1]
Hi there, I stumbled upon your repo while looking for some solution for Advent of Code 2023. I am fairly new to this event as well as "Go" itself. I found a small issue with you code in SumOfLine function. The issue in your code lies in how you're converting characters to integers. In the SumOfLine function instead of using int(ch), you should use int(ch - '0') to convert the character to its corresponding integer value. The ASCII value of '0' is 48, so subtracting '0' from any digit character will give you the correct integer value.

```go
func SumOfLine(line string) (int, error) {
    first, last := 0, 0

    for i := 0; i < len(line); i++ {
        ch := line[i]
        if utils.IsDigit(ch) {
            first = int(ch - '0')

            for j := len(line) - 1; j >= i; j-- {
                ch = line[j]
                if utils.IsDigit(ch) {
                    last = int(ch - '0')
                    break
                }
            }
            break
        }
    }

    convertedDigit, err := strconv.Atoi(fmt.Sprintf("%d%d", first, last))
    if err != nil {
        return 0, fmt.Errorf("unable to convert string to integer: %w", err)
    }

    return convertedDigit, nil
}
```

**Comment by Aadv1k** [comment]
Hey man, thanks for dropping by. You are correct in your observation! I'll fix this right away, I must thank you for going through the solutions, it feels good when a fellow developer cares about your code enough to go through it haha. I think the least I can do is credit you on the `README.md` thanks again, and I hope you have a good rest of the day. Cheers 🥂

Best, 
Aadvik

**Comment by Mr-Unforgettable** [comment]
Thanks. Mention not. I was just dealing with go modules and workspaces. So I decided to work on a AOC2023 problem with Go. I am relatively new in this language. I have a question regarding your though behind not working with go.work? I am trying to understand when and where to use go.work. If you have any info regarding this please share it with me. I am currently facing some problems with go dependency management.

**Comment by Aadv1k** [comment]
Well, I never got the chance to use it in that way. Currently the main module is AdventOfGo2023, in which each day is a package. I would have used `go.work` but
- The structure isn't that complicated
- I am not using any thirdparty modules 
Outside of that, even I have very little experience with go, and I just follwed https://go.dev/doc/effective_go <- this as a guide

**Comment by Mr-Unforgettable** [comment]
Thanks for your suggestion. I will look into it to understand it more deeply.
